### ISSUE TITLE
program doesn't start

### ISSUE THREAD

**Issue by rbalykov** [jeffmikels/timecode_tools#1]
File "./timecode_generator.py", line 258
    print(f'   COMPUTING:  {total_samples}:{sample}  --  {pct}%', end='\r')

**Comment by jeffmikels** [comment]
Are you using Python 3.6 or higher?

**Comment by rbalykov** [comment]
nope, 3.5, thanks

**Comment by jeffmikels** [comment]
To make it work with 3.5, you simply need to change the f-strings to use the older string formatting methods. If you can upgrade to 3.6, do that, but if you can't just change the strings. If you need help, I can help.

**Comment by rbalykov** [comment]
just change to "print 'some text ', var, ' some new text".
I got it. Thanks.
