### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rdoursenaud** [jeffmikels/timecode_tools#4]
Hi,

I plan on using snippets of your code for a project: https://github.com/EMATech/Network-Studio-Clock

Could you please clarify under which license your code is released?
Ideally, this would be released under MIT just like the libraries it depends upon.
Unless I missed it, I’ve not been able to find this information anywhere.

Thanks!

**Comment by jeffmikels** [comment]
I just posted the MIT license now.
